version: '3.8'
services:
  django:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: streaming

  antmedia:
    image: nibrev/ant-media-server  # Replace this with the correct image you used
    ports:
      - "5080:5080"
      - "1935:1935"
      - "5443:5443"
    restart: unless-stopped
